spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

indexing-settings:
  sites:

    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://moldremoval.ru
      name: Ремовал


myStringValue: WebScanner
web:
  scanner:
    url: https://skillbox.ru/
    visited:
      urls:
        - https://www.lenta.ru
        - https://www.skillbox.ru
        - https://www.playback.ru